HW Lesson4
mtkachenk0/saltedge-courses2020 pull request #24
Opened 2020-02-22 12:22 UTC by serghei-rubailo

2020-02-28 08:07 UTC, jeneamocan requested changes

2020-02-28 08:07 UTC, jeneamocan commented on README.md
> -# saltedge-courses2020
You've done a great job! There's just one thing you should do - discard the changes on the README file

2020-02-29 09:06 UTC, serghei-rubailo commented on README.md
> -# saltedge-courses2020
Ok. Done.
README.md was discarded to "master" state.

2020-02-29 12:48 UTC, jeneamocan approved these changes

2020-02-29 12:49 UTC, jeneamocan commented
Everything's great, just add the file into a folder, same as here https://github.com/mtkachenk0/saltedge-courses2020/pull/39

2020-03-01 08:48 UTC, serghei-rubailo commented
> Everything's great, just add the file into a folder, same as here #39

Ok. Done.
"rubailo_s" directory was created. lesson4 HW file was moved to new directory.

2020-03-01 09:56 UTC, merged